Repository TechUni2020/member-site, pull requests merged in 2022-08, with the labels that each got.

#58 【WIP】ログアウトアイコン・fieldなど追加・メンバー側で取得表示
  .eslintrc.js
  src/components/feature/Card/index.tsx
  src/components/feature/SettingModal.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Sidebar.tsx
  src/components/ui-libraries/AppButton.tsx
  src/components/ui-libraries/AppToast.tsx
  src/components/ui-libraries/AuthProvider.tsx
  src/components/ui-libraries/icon/DeleteIcon.tsx
  src/components/ui-libraries/icon/LogoutIcon.tsx
  src/components/ui-libraries/icon/index.ts
  src/components/utils/constants/link.ts
  src/components/utils/constants/university.ts
  src/components/utils/libs/firebase.ts
  src/global-states/atoms.ts
  src/pages/_app.tsx
  src/pages/login/index.tsx
  src/pages/member/index.tsx
  src/pages/root/index.tsx
  src/pages/signup/index.tsx
Labels: WIP

#70 pnpmの採用
  .npmrc
  package.json
  pnpm-lock.yaml
  src/components/feature/SettingModal.tsx
  yarn.lock
Labels: app

#72 tailwindのorderをCard以外全部治した
  src/components/feature/SettingModal.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Sidebar.tsx
  src/components/page/Login/index.tsx
  src/components/page/Member/index.tsx
  src/components/page/SignUp/index.tsx
  src/components/ui-libraries/AppLoading.tsx
  src/components/ui-libraries/icon/BellIcon.tsx
  src/components/ui-libraries/icon/CalendarIcon.tsx
  src/components/ui-libraries/icon/DeleteIcon.tsx
  src/components/ui-libraries/icon/GitHubIcon.tsx
  src/components/ui-libraries/icon/HomeIcon.tsx
  src/components/ui-libraries/icon/InfoIcon.tsx
  src/components/ui-libraries/icon/InstagramIcon.tsx
  src/components/ui-libraries/icon/LogoutIcon.tsx
  src/components/ui-libraries/icon/MemberIcon.tsx
  src/components/ui-libraries/icon/SettingIcon.tsx
  src/components/ui-libraries/icon/StudyIcon.tsx
  src/components/ui-libraries/icon/TextIcon.tsx
  src/components/ui-libraries/icon/TwitterIcon.tsx
  src/components/ui-libraries/icon/UsersIcon.tsx
Labels: bug

#66 メンバー
  src/components/feature/Card/index.tsx
  src/components/feature/MemberCard/MemberCard.tsx
  src/components/feature/SettingModal.tsx
  src/components/page/Member/MemberDetail.tsx
  src/components/page/Member/index.tsx
  src/components/utils/constants/field.ts
  src/components/utils/constants/university.ts
  src/global-states/atoms.ts
  src/pages/member/[id].tsx
Labels: app

#73 イベントページ
  .eslintrc.js
  src/components/feature/Member/FieldInterest.tsx
  src/components/feature/Member/MemberCard.tsx
  src/components/feature/Member/MemberProfileIcon.tsx
  src/components/feature/Member/ProfileImg.tsx
  src/components/feature/MemberStatusEditContentsModal.tsx
  src/components/feature/ProfileEditContentsModal.tsx
  src/components/layout/Sidebar.tsx
  src/components/page/Admin/AdminDetail.tsx
  src/components/page/Admin/index.tsx
  src/components/page/Events/index.tsx
  src/components/page/Member/MemberDetail.tsx
  src/components/page/Member/index.tsx
  src/components/ui-libraries/AuthProvider.tsx
  src/components/ui-libraries/icon/EventIcon.tsx
  src/components/ui-libraries/icon/index.ts
  src/components/utils/constants/link.ts
  src/components/utils/libs/firebase/event.ts
  src/components/utils/libs/firebase/index.ts
  src/components/utils/libs/firebase/users.ts
  src/global-states/atoms.ts
  src/pages/event/index.tsx
Labels: app

#87 Tech.Uniアイコンと、Homeのアイコンの大きさ、位置を揃える
  src/components/layout/Header.tsx
Labels: WIP

#79 signupページとユーザー遷移
  src/components/page/SignUp/Step1.tsx
  src/components/page/SignUp/Step2.tsx
  src/components/page/SignUp/Step3.tsx
  src/components/page/SignUp/Step4.tsx
  src/components/page/SignUp/StepCircle.tsx
  src/components/page/SignUp/index.tsx
  src/components/ui-libraries/AppButton.tsx
  src/components/ui-libraries/AuthProvider.tsx
  src/components/utils/constants/field.ts
  src/pages/_app.tsx
Labels: app

#83 管理者のみadminページを見れるように
  src/components/feature/Member/MemberCard.tsx
  src/components/feature/MemberStatusEditContentsModal.tsx
  src/components/feature/ProfileEditContentsModal.tsx
  src/components/page/Admin/AdminDetail.tsx
  src/components/page/Admin/index.tsx
  src/components/page/Events/index.tsx
  src/components/page/Home/index.tsx
  src/components/page/Member/MemberDetail.tsx
  src/components/page/Member/index.tsx
  src/components/page/SignUp/Step2.tsx
  src/components/ui-libraries/AuthProvider.tsx
  src/components/utils/constants/link.ts
  src/components/utils/libs/firebase/index.ts
  src/components/utils/libs/firebase/users.ts
  src/global-states/atoms.ts
  src/hooks/event/useFetchEventList.ts
  src/hooks/user/useFetchEventOrganizer.ts
  src/hooks/user/useFetchUser.ts
  src/hooks/user/useFetchUserList.ts
  src/modules/event/event.entity.ts
  src/modules/event/event.repository.ts
  src/modules/event/index.ts
  src/modules/user/index.ts
  src/modules/user/user.repository.ts
  src/pages/_app.tsx
Labels: admin
